### ISSUE TITLE
Any clue how to add Wake on LAN?

### ISSUE THREAD

**Issue by saschabrockel** [DaviPtrs/hass-unified-remote#20]
Hey there. Thanks for your great work. Finally, I found an alternative to using Tasker with Unified Remote. So I don't need an Android phone for that.

Now I'm wondering why you haven't included Wake on LAN in the remote defaults of power. I've added `"@wol"` as control in the `remotes.yaml `now but it does not work. Not sure if it is a problem but Home Assistant won't let me just write @wol for a service_data action. I have to put it in 
quotation marks.

![image](https://github.com/DaviPtrs/hass-unified-remote/assets/33376463/c43c2311-e7db-4c99-8af9-4ca99eafbd68)
But it seems to be @wol or am I wrong?

**Comment by Wol** [comment]
You rang? 😂

**Comment by saschabrockel** [comment]
@Wol lol sorry hahahaha

**Comment by DaviPtrs** [comment]
hey @saschabrockel,

well, actually you can't do that. The integration requires you computer being turned on, because it works by connecting to the Unified Remote client on the target computer, so if the computer is off, it won't be able to call any remotes. To use Wake on Lan, you can use the built in wol on home assistant: https://www.home-assistant.io/integrations/wake_on_lan/
