### ISSUE TITLE
After the last update a few moments the commands don't work

### ISSUE THREAD

**Issue by frederico0102** [DaviPtrs/hass-unified-remote#7]
Hello, after the last update v1.1.1 it happened that after a long time with HA active, it happens that the send commands stop working and only return after restarting HA.
I will try to get more information about the problem to complement the case.

**Comment by frederico0102** [comment]
another thing that also occurs is that if the Unified Remote server on which he was sending commands goes offline and then goes online again, the commands are no longer sent.
Ex: when I restart the computer that contains the server.
(the problem is not on the server as the commands via the web or Unified remote application keep working)

**Comment by DaviPtrs** [comment]
Hello, I've been experiencing this issue last days, I solved this by decreasing ```retry_delay``. Set this setting to around 30 and you won't have problems anymore.

**Comment by DaviPtrs** [comment]
Decreasing the "retry_delay" solve the first issue, but the second (on the computer restart) is apparently happening here too. I will try to fix this soon.

**Comment by frederico0102** [comment]
Okay I'll test it, thanks

**Comment by guegrer** [comment]
i update to 0.118 same issue your right Davi ;)

**Comment by DaviPtrs** [comment]
The issue when you restart the host still happening, and I just update to 0.118 =(

**Comment by frederico0102** [comment]
Even after updating mine, I still have the problem after restarting the server

**Comment by Siridar** [comment]
Hi, same issue here.
Commands work only just after several seconds after HomeAssistant server is restarted. After that I get such errors:


```
Logger: custom_components.unified_remote
Source: custom_components/unified_remote/__init__.py:150
Integration: Unified Remote Control
First occurred: 1:49:30 PM (1 occurrences)
Last logged: 1:49:30 PM
Unable to call remote. Clevo is unavailable. 
```

```
Logger: custom_components.unified_remote.cli.computer
Source: custom_components/unified_remote/cli/computer.py:38
Integration: Unified Remote Control
First occurred: 1:49:30 PM (1 occurrences)
Last logged: 1:49:30 PM
Unable to call remote. Clevo is unavailable.
```

Plugin config:
```
unified_remote:
  hosts:
    - host: 192.168.20.6
      name: Clevo
      port: 9510
    - host: 192.168.20.5
      name: Thinkpad
      port: 9510
  retry_delay: 60
```

**Comment by DaviPtrs** [comment]
@Siridar I fixed the reconnection problem, try to update the integration, if it doesn't solve, try to decrease the retry_delay

**Comment by Madd0g** [comment]
hey, thanks for this great integration!

I'm having a similar issue where after crashing or connectivity loss of the UR host, the integration is creating multiple clients (I see on the manager page, multiple clients of type "web" being created, not on every command sent, but maybe after every command that took a long time?)

I tried lowering the retry_delay to 15, it definitely makes things better, but for some reason, it takes a while to become actually reliable again if it has connection issues.

It recovers and commands start going through, but it's still spotty for a few minutes after a connection loss. It feels a little related to the "web clients" on the manager page, because it seems like even when they do connect - the integration is giving up on the connection even if it's succeeded?

Also, noticed that HA startup takes a long time if the UR host is down, it says on the bottom "waiting for unified_remote to start". If the connection is only for one-way commands, should it connect on startup and not on-demand?
